### ISSUE TITLE
flip method not exported on Julia v1.6

### ISSUE THREAD

**Issue by MRoqueta** [archermarx/PartialFunctions.jl#2]
On Julia v1.6 it seems the `flip` method is not exported by the PartialFunctions module for me, I get the following
```
julia> names(PartialFunctions)
3-element Vector{Symbol}:
 :$
 :<|
 :PartialFunctions
```

I cloned the package and made a change to the `export` statement on `PartialFunctions.jl`, from
```
export $, <|
```
to
```
export $
export <|
```
and it seemed to solve the problem, although I am not sure why. I can make a pull request with the changes.
Thanks!

**Comment by archermarx** [comment]
Oh interesting. Yes please make the PR and I'd be happy to merge it!
