### ISSUE TITLE
1.1.0 not registered

### ISSUE THREAD

**Issue by tfiers** [archermarx/PartialFunctions.jl#4]
Any reason for this? https://juliahub.com/ui/Packages/PartialFunctions/dX5Z0/ gives 1.0.4

**Comment by archermarx** [comment]
Hmm, interesting. I can look into this

**Comment by archermarx** [comment]
With the recent PR by MRoqueta, i've updated to 1.1.1, and will see if retriggering the RegistratorBot works

**Comment by archermarx** [comment]
OK, 1.1.1 has been merged into the general registry, now just waiting for tagbot to trigger

**Comment by archermarx** [comment]
v1.1.1 has now been tagged and I have verified it is now in the general registry.

**Comment by tfiers** [comment]
Awesome, I could indeed install the newest version from the general reg. Thanks!
