### ISSUE TITLE
Is there a way to run a function once the number of arguments "saturates"?

### ISSUE THREAD

**Issue by davibarreira** [archermarx/PartialFunctions.jl#6]
Hey, thanks for this package! I've been playing around with it in order to implement some functional programming stuff.
I was wondering if there is a way to run a function that has a limited amount of arguments, without having to explicitly call the `<| ()`. For example
```julia
f(x,y) = 2(x+y)
f $ 1 $ 2 # This should immediately run the function
```

**Comment by archermarx** [comment]
Hmm, I'm not sure. In general due to the dynamic nature of Julia, it isn't always easy to figure out how many arguments a function should have, Consider the following:

```julia
f(x , y) = x + y
f(x, y, z) = x + y + z
f $ 1 $ 2 # What should this do? 
```

**Comment by davibarreira** [comment]
Yeah, I thought this was the possible reason why this wouldn't be possible.
