### ISSUE TITLE
Release v1.2

### ISSUE THREAD

**Issue by avik-pal** [archermarx/PartialFunctions.jl#8]
It seems like there is a 1.2 tag on github but it never got released on the registry

https://github.com/JuliaRegistries/General/blob/master/P/PartialFunctions/Versions.toml

**Comment by archermarx** [comment]
Huh! That's weird. I can try and fix that shortly

**Comment by archermarx** [comment]
Got it scheduled to merge in the next round

https://github.com/JuliaRegistries/General/pull/94171

**Comment by avik-pal** [comment]
Thanks!
